"""Bakeoff bundle oracle (glm-5p2 agentic gate) — three independent backend fixes.

Each test pins ONE small fix. Authored RED on branch bakeoff/oracle-bundle.
The executor must make these pass by editing SOURCE only — do NOT edit this file
or any other tests/ file.

  B5  — promote._day must render the UTC calendar date, not the local-tz date.
  I7a — `pkms new` must not silently collide; a duplicate title gets a -<n> suffix.
  F6  — indexed note paths must use '/' separators (URL-safe), never '\\'.
"""

from datetime import UTC, datetime

import pytest
from typer.testing import CliRunner

import pkms.cli as cli
from pkms import promote
from pkms.db import connect
from pkms.indexer import index_vault

runner = CliRunner()


# ---- B5: provenance day is the UTC date, not the local-timezone date ----
def test_b5_day_uses_utc():
    # 2023-11-14T00:30:00Z — just past UTC midnight. In any timezone behind UTC the
    # local clock is still on the 13th, so a local-tz conversion renders the wrong day.
    epoch = 1699921800
    local_day = datetime.fromtimestamp(epoch).date().isoformat()
    utc_day = datetime.fromtimestamp(epoch, tz=UTC).date().isoformat()
    if local_day == utc_day:
        pytest.skip("CI runner's timezone has zero UTC offset — test requires non-UTC tz")
    assert promote._day(epoch) == utc_day


# ---- I7a: `pkms new` suffixes a colliding slug instead of overwriting ----
def test_i7a_new_slug_collision(tmp_path, monkeypatch):
    vault = tmp_path / "vault"
    vault.mkdir()
    monkeypatch.setattr(cli, "VAULT", vault)
    monkeypatch.setattr(cli.subprocess, "Popen", lambda *a, **kw: None)  # never spawn an editor

    assert runner.invoke(cli.app, ["new", "My Note"]).exit_code == 0
    assert runner.invoke(cli.app, ["new", "My Note"]).exit_code == 0

    first = vault / "my-note.md"
    second = vault / "my-note-2.md"
    md = sorted(p.name for p in vault.glob("*.md"))
    assert first.exists() and second.exists(), (
        f"a second `new` with a colliding title must create my-note-2.md without "
        f"overwriting the first; vault has: {md}"
    )
    assert "title: My Note" in first.read_text(encoding="utf-8")
    assert "title: My Note" in second.read_text(encoding="utf-8")


# ---- F6: stored/returned index paths are forward-slash, never backslash ----
def test_f6_index_paths_forward_slash(tmp_path):
    vault = tmp_path / "vault"
    (vault / "projects").mkdir(parents=True)
    (vault / "projects" / "alpha.md").write_text(
        "---\ntitle: A\ncreated: 2026-01-01\n---\n\nbody\n", encoding="utf-8"
    )
    idx = tmp_path / ".index"
    index_vault(vault, idx)

    conn = connect(idx)
    paths = [r[0] for r in conn.execute("SELECT path FROM notes").fetchall()]
    conn.close()

    assert paths, "no notes were indexed"
    nested = next(p for p in paths if "alpha" in p)
    assert "/" in nested and "\\" not in nested, (
        f"stored note path must use '/' separators, got {nested!r}"
    )
