"""Bakeoff I3 oracle (glm-5p2 agentic gate) — dedupe the "one next action per note" SQL.

The identical projects-first, one-open-task-per-note ranking query is duplicated in
src/pkms/cli.py (the `tasks` default) and src/pkms/today.py (`_next_actions`). They will
drift. Extract ONE shared helper `tasks.next_action_per_note(conn)` and call it from both.

Authored RED on branch bakeoff/oracle-I3. The executor edits SOURCE only (cli.py, today.py,
tasks.py) — do NOT edit this file or any other tests/ file. Existing test_today.py /
test_cli.py already pin that both call sites' OUTPUT is preserved; these tests add the
helper's behavioral contract plus the anti-drift check that the duplication is actually gone.
"""

from pathlib import Path

import pkms.cli
import pkms.today
from pkms import tasks
from pkms.db import connect
from pkms.indexer import index_vault


# ---- behavioral contract of the shared helper ----
def test_i3_shared_helper_ranks_one_open_action_per_note(vault, index_dir):
    index_vault(vault, index_dir)
    conn = connect(index_dir)
    try:
        rows = tasks.next_action_per_note(conn)
    finally:
        conn.close()

    notes = [r["note_path"] for r in rows]
    assert notes, "helper returned no next actions"
    assert len(notes) == len(set(notes)), "must be one next action per note"
    assert notes[0].startswith("projects"), "projects notes must rank first"
    by_note = {r["note_path"]: r["text"] for r in rows}
    # alpha.md has an open task and a done task — the OPEN one is the next action
    assert by_note["projects/alpha.md"] == "open task one"  # F6: paths stored forward-slash
    # no inbox captures, no closed tasks leak in
    assert all(not n.startswith("inbox") for n in notes)


# ---- anti-drift: both call sites delegate to the one helper; no duplicated SQL ----
def test_i3_both_sites_delegate_to_shared_helper():
    cli_src = Path(pkms.cli.__file__).read_text(encoding="utf-8")
    today_src = Path(pkms.today.__file__).read_text(encoding="utf-8")

    assert "next_action_per_note" in cli_src, "cli `tasks` default must call the shared helper"
    assert "next_action_per_note" in today_src, "today._next_actions must call the shared helper"

    # the duplicated ranking query must no longer live inline at either call site
    assert "GROUP BY t.note_path" not in cli_src, "inline ranking SQL still duplicated in cli.py"
    assert "GROUP BY t.note_path" not in today_src, (
        "inline ranking SQL still duplicated in today.py"
    )
