"""Delegate typeface research to the local LLM (gpt-oss-20b) via LM Studio's
OpenAI-compatible endpoint, bypassing the MCP bridge's 30s call ceiling.

The local-llm-delegation skill prescribes this scripted path for any call that
may include JIT-load time. Saves the raw output to TYPEFACE-RESEARCH.md for
review + integration by the orchestrator (cloud model).
"""
import json
import sys
import urllib.request

URL = "http://localhost:1234/v1/chat/completions"
MODEL = "openai/gpt-oss-20b"
OUT = r"K:\Projects\PKMS\spike\newtab-firefox\TYPEFACE-RESEARCH.md"

SYSTEM = (
    "You are a typography consultant for a personal-knowledge app's new-tab page. "
    "Complete the task thoroughly and concretely. Output under explicit headings "
    "only, no prose outside them. Be opinionated and specific — not generic type advice."
)

USER = """You are a typography consultant for a personal-knowledge app's new-tab page.

The current design uses Fraunces (serif display) + Inter (humanist sans) + JetBrains Mono, loaded from Google Fonts. The aesthetic is "authored morning briefing on warm cream paper" — editorial, calm, single ochre accent, one loud moment reserved for completion. It is deliberately NOT a Momentum/dashboard look. Constraints:
- The page loads on EVERY new tab, so web-font payload matters (perceived load).
- Must degrade gracefully offline (system-font CSS stacks as fallback).
- Distinctive > trendy; this should feel designed, not generic.

The user feels the current typeface selection "needs work" but gave no specifics.

Produce, under explicit headings:

### 1. Diagnosis
What's likely weak about Fraunces+Inter+JetBrains Mono for THIS use (3-5 bullets, concrete — not generic type advice). Consider: does Inter read as "default SaaS" and undercut the editorial intent? Is Fraunces's optical-size axis doing work here or is it flourish?

### 2. Three candidate pairings
For each: serif display + body sans + mono. Name exact families available on Google Fonts OR via open-source self-host (no proprietary/licensed faces). One paragraph each on WHY it fits the editorial-briefing aesthetic, and the trade-off vs the current set. Prefer pairings where the serif has real personality and the sans is NOT Inter/Roboto/system-default.

### 3. Recommendation
Pick ONE pairing. Give a one-line rationale.

### 4. CSS type-scale block
A complete `:root { ... }` block defining --serif, --sans, --mono families (with full fallback stacks) and a fluid type-scale (--step--1 through --step-5) using clamp(). The scale should make a re-entry lede the largest element on the page (the glance anchor) at a max ~5rem on wide viewports, stepping down on narrow. Match the existing --step variable names so it's a drop-in replacement."""

payload = json.dumps({
    "model": MODEL,
    "messages": [
        {"role": "system", "content": SYSTEM},
        {"role": "user", "content": USER},
    ],
    "temperature": 0.4,
    "max_tokens": 3000,
}).encode("utf-8")

req = urllib.request.Request(
    URL, data=payload, headers={"Content-Type": "application/json"},
    method="POST",
)
print(f"delegating to {MODEL} ...", flush=True)
try:
    with urllib.request.urlopen(req, timeout=600) as r:  # noqa: S310 - localhost
        resp = json.loads(r.read().decode("utf-8"))
except Exception as e:
    print(f"FAILED: {type(e).__name__}: {e}", flush=True)
    sys.exit(1)

content = resp["choices"][0]["message"]["content"]
finish = resp["choices"][0].get("finish_reason")
usage = resp.get("usage", {})

header = (
    "# Typeface research (local-LLM delegated)\n\n"
    f"> Generated by `{MODEL}` via LM Studio, 2026-06-24. "
    "Pre-review raw output from a `local-llm-delegation` task (see plan Task 3). "
    f"finish_reason={finish} · tokens={usage}\n\n"
    "---\n\n"
)
with open(OUT, "w", encoding="utf-8") as f:
    f.write(header + content + "\n")

print(f"wrote {OUT}", flush=True)
print(f"finish_reason={finish}  usage={usage}", flush=True)
print(f"content length: {len(content)} chars", flush=True)
